### PR TITLE
Optionally gzip backup

### PR DESCRIPTION
**Pull request by manics**
See https://github.com/ome/prod-playbooks/pull/285#issuecomment-712709349

Tag: `0.1.3`

### CODE REVIEW

**Comment by sbesson** [comment]
Changes look good and the new Molecule scenario is covering the new compress option. Is there any requirement/recommendation in terms of the `postgresql_backup_filename_format` if `postgresql_backup_compress` is set to `True`? Or would `.gz` be auto-appended to the filename?

**Comment by manics** [comment]
There's no naming requirement since pgdump can't read gzip directly, it'll always require a manual decompression step so it's up to us. Do you think `.gz` should only be appended for the default `postgresql_backup_filename_format`, or unconditionally?

**Comment by sbesson** [comment]
At least my experience is that `gunzip/gzip` transparently appends/removes the `.gz` extension without any argument. Based on this, I would not mind it having it appended unconditionally to the `postgresql_backup_filename_format` independently of whether it is the default or a custom value. Either way, we can use the README to clarify the expectation.

**Review by sbesson — APPROVED** [review]
Merging and tagging as `0.2.0` as this is a new backwards compatible feature.

**Pull request merged**
